### ISSUE TITLE
重新编译的时候需要依赖go包

### ISSUE THREAD

**Issue by Allen-LPL** [wangriyu/docker-grafana#1]
重新编译的时候需要依赖go包, 这样子就相当于还要重新在本地编译打包好以后才能使用了, @wangriyu 你这里能直接提供编译好的版本么?

**Comment by wangriyu** [comment]
我这倒是能编译，但是镜像很大，不好传

**Comment by Allen-LPL** [comment]
嗯嗯， 我这里自己编译完成了， 谢谢你的分享


| |
大喝一声彩
|
|
liupengliang1012@126.com
|
签名由网易邮箱大师定制


在2019年03月13日 17:36，鱼乐<notifications@github.com> 写道：

我这倒是能编译，但是镜像很大，不好传
