### ISSUE TITLE
在构建到第20步时，报错

### ISSUE THREAD

**Issue by linkght-inject** [wangriyu/docker-grafana#2]
报错信息：
/bin/sh: 1: ./node_modules/.bin/grunt: not found
The command '/bin/sh -c ./node_modules/.bin/grunt build' returned a non-zero code: 127
make: *** [build-docker-full] Error 127

构建记录：
[root@node1 docker-grafana]# sh run.sh 
docker build --tag grafana/grafana:dev .
Sending build context to Docker daemon  49.05MB
Step 1/36 : FROM golang:1.11
 ---> 943a5a7ecac8
Step 2/36 : WORKDIR $GOPATH/src/github.com/grafana/grafana
 ---> Using cache
 ---> 9cd3ef638b92
Step 3/36 : COPY Gopkg.toml Gopkg.lock ./
 ---> Using cache
 ---> b5252253e80e
Step 4/36 : COPY vendor vendor
 ---> Using cache
 ---> a7e66e8fe3ec
Step 5/36 : ARG DEP_ENSURE=""
 ---> Using cache
 ---> 7e20138369f3
Step 6/36 : RUN if [ ! -z "${DEP_ENSURE}" ]; then       go get -u github.com/golang/dep/cmd/dep &&       dep ensure --vendor-only;     fi
 ---> Using cache
 ---> 628b706deb4d
Step 7/36 : COPY pkg pkg
 ---> Using cache
 ---> 766ad466f416
Step 8/36 : COPY build.go build.go
 ---> Using cache
 ---> eb681379c7ac
Step 9/36 : COPY package.json package.json
 ---> Using cache
 ---> 7c03a2410a24
Step 10/36 : RUN go run build.go build
 ---> Using cache
 ---> 3921e25669b6
Step 11/36 : FROM node:8
 ---> 8c51cec97ebf
Step 12/36 : WORKDIR /usr/src/app/
 ---> Using cache
 ---> de677f8e426d
Step 13/36 : COPY package.json yarn.lock ./
 ---> Using cache
 ---> 800eacdbf71a
Step 14/36 : RUN yarn install --pure-lockfile --no-progress
 ---> Using cache
 ---> 7106be56d8e3
Step 15/36 : COPY Gruntfile.js tsconfig.json tslint.json ./
 ---> Using cache
 ---> 6fb7800e4ffc
Step 16/36 : COPY public public
 ---> Using cache
 ---> 85c668deb9cf
Step 17/36 : COPY scripts scripts
 ---> Using cache
 ---> 810e340140c2
Step 18/36 : COPY emails emails
 ---> Using cache
 ---> a1ccb690c04b
Step 19/36 : ENV NODE_ENV production
 ---> Using cache
 ---> c98c38b9b5f0
Step 20/36 : RUN ./node_modules/.bin/grunt build
 ---> Running in 073d688ea8f3
/bin/sh: 1: ./node_modules/.bin/grunt: not found
The command '/bin/sh -c ./node_modules/.bin/grunt build' returned a non-zero code: 127
make: *** [build-docker-full] Error 127
run.sh: line 19: grafana/grafana:dev: No such file or directory
build docker image:  success

**Comment by wangriyu** [comment]
你是用的 docker for mac 吗，https://github.com/grafana/grafana/blob/master/README.md#building-anywhere-slower 这里提到内存限制小于 2GB, grunt build 会失败

**Comment by linkght-inject** [comment]
thanks,it's done!
